export type MunicipiosPorProvincia = Record<string, readonly string[]>;

export const MUNICIPIOS_POR_PROVINCIA: MunicipiosPorProvincia = {
  'Álava': ['Vitoria-Gasteiz', 'Llodio', 'Amurrio', 'Salvatierra', 'Laguardia', 'Oyón-Oion', 'Iruña Oka', 'Elburgo/Burgelu'],
  'Albacete': ['Albacete', 'Hellín', 'Villarrobledo', 'Almansa', 'La Roda', 'Caudete', 'Tobarra', 'Alcaraz', 'Tarazona de la Mancha'],
  'Alicante': ['Alicante/Alacant', 'Elche/Elx', 'Torrevieja', 'Orihuela', 'Benidorm', 'Alcoy/Alcoi', 'Elda', 'San Vicente del Raspeig/Sant Vicent del Raspeig', 'Dénia', 'Petrer'],
  'Almería': ['Almería', 'Roquetas de Mar', 'El Ejido', 'Adra', 'Níjar', 'Huércal-Overa', 'Vícar', 'Cuevas del Almanzora', 'Berja'],
  'Asturias': ['Oviedo', 'Gijón', 'Avilés', 'Siero', 'Langreo', 'Mieres', 'Castrillón', 'San Martín del Rey Aurelio', 'Corvera de Asturias', 'Villaviciosa'],
  'Ávila': ['Ávila', 'Arévalo', 'Sotillo de la Adrada', 'Las Navas del Marqués', 'Candeleda', 'Piedralaves', 'El Tiemblo', 'El Barco de Ávila', 'Mombeltrán'],
  'Badajoz': ['Badajoz', 'Mérida', 'Don Benito', 'Almendralejo', 'Villanueva de la Serena', 'Zafra', 'Montijo', 'Olivenza', 'Jerez de los Caballeros', 'Llerena'],
  'Barcelona': ['Barcelona', "L'Hospitalet de Llobregat", 'Badalona', 'Sabadell', 'Terrassa', 'Santa Coloma de Gramenet', 'Sant Cugat del Vallès', 'Mataró', 'Sant Boi de Llobregat', 'Cornellà de Llobregat', 'Manresa', 'Castelldefels', 'Viladecans', 'El Prat de Llobregat', 'Granollers'],
  'Burgos': ['Burgos', 'Miranda de Ebro', 'Aranda de Duero', 'Briviesca', 'Medina de Pomar', 'Villarcayo', 'Lerma', 'Salas de los Infantes'],
  'Cáceres': ['Cáceres', 'Plasencia', 'Navalmoral de la Mata', 'Trujillo', 'Coria', 'Alcántara', 'Guadalupe', 'Jaraíz de la Vera', 'Talayuela', 'Miajadas'],
  'Cádiz': ['Cádiz', 'Jerez de la Frontera', 'Algeciras', 'San Fernando', 'El Puerto de Santa María', 'Chiclana de la Frontera', 'Sanlúcar de Barrameda', 'Rota', 'Barbate', 'Conil de la Frontera'],
  'Cantabria': ['Santander', 'Torrelavega', 'Castro-Urdiales', 'Camargo', 'Piélagos', 'El Astillero', 'Santa Cruz de Bezana', 'Laredo', 'Reinosa', 'Los Corrales de Buelna'],
  'Castellón': ['Castellón de la Plana', 'Villarreal', 'Borriol', "Vall d'Uixó", 'Benicàssim', 'Oropesa del Mar', 'Benicarló', 'Vinaròs', 'Segorbe', 'Burriana'],
  'Ciudad Real': ['Ciudad Real', 'Puertollano', 'Tomelloso', 'Alcázar de San Juan', 'Valdepeñas', 'Manzanares', 'Daimiel', 'La Solana', 'Miguelturra', 'Campo de Criptana'],
  'Córdoba': ['Córdoba', 'Lucena', 'Puente Genil', 'Montilla', 'Priego de Córdoba', 'Cabra', 'Baena', 'Peñarroya-Pueblonuevo', 'Fernán-Núñez', 'La Carlota'],
  'Cuenca': ['Cuenca', 'Tarancón', 'Quintanar del Rey', 'Las Pedroñeras', 'San Clemente', 'Mota del Cuervo', 'Motilla del Palancar', 'Iniesta', 'Horcajo de Santiago'],
  'Girona': ['Girona', 'Figueres', 'Blanes', 'Lloret de Mar', 'Olot', 'Salt', 'Palafrugell', 'Sant Feliu de Guíxols', 'Ripoll', 'Banyoles'],
  'Granada': ['Granada', 'Motril', 'Armilla', 'Las Gabias', 'Atarfe', 'Loja', 'Almuñécar', 'Baza', 'Guadix', 'Santa Fe', 'Albolote'],
  'Guadalajara': ['Guadalajara', 'Azuqueca de Henares', 'Alovera', 'Sigüenza', 'El Casar', 'Torrejón del Rey', 'Molina de Aragón', 'Cabanillas del Campo', 'Yunquera de Henares'],
  'Guipúzcoa': ['Donostia-San Sebastián', 'Irún', 'Errenteria', 'Eibar', 'Tolosa', 'Hernani', 'Pasaia', 'Lasarte-Oria', 'Andoain', 'Zarautz'],
  'Huelva': ['Huelva', 'Lepe', 'Almonte', 'Isla Cristina', 'Ayamonte', 'Moguer', 'Punta Umbría', 'La Palma del Condado', 'Bollullos par del Condado', 'Rociana del Condado'],
  'Huesca': ['Huesca', 'Monzón', 'Barbastro', 'Binéfar', 'Fraga', 'Jaca', 'Sabñánigo', 'Tamarit de Litera', 'Sariñena', 'Almudévar'],
  'Islas Baleares': ['Palma de Mallorca', 'Calvià', 'Manacor', 'Llucmajor', 'Inca', 'Maó-Mahón', 'Ciutadella de Menorca', 'Ibiza', 'Santa Eulalia del Río', 'Sant Antoni de Portmany'],
  'Jaén': ['Jaén', 'Linares', 'Andújar', 'Úbeda', 'Martos', 'Alcalá la Real', 'Baeza', 'Torredelcampo', 'Alcaudete', 'Mancha Real'],
  'A Coruña': ['A Coruña', 'Santiago de Compostela', 'Ferrol', 'Narón', 'Oleiros', 'Arteixo', 'Carballo', 'Ribeira', 'Culleredo', 'Betanzos'],
  'La Rioja': ['Logroño', 'Calahorra', 'Arnedo', 'Haro', 'Alfaro', 'Santo Domingo de la Calzada', 'Nájera', 'Lardero', 'Villamediana de Iregua', 'Autol'],
  'Las Palmas': ['Las Palmas de Gran Canaria', 'Telde', 'Santa Lucía de Tirajana', 'Arucas', 'Ingenio', 'Gáldar', 'Agüimes', 'San Bartolomé de Tirajana', 'Mogán', 'Teror'],
  'León': ['León', 'Ponferrada', 'San Andrés del Rabanedo', 'Villaquilambre', 'Astorga', 'La Bañeza', 'Bembibre', 'Valencia de Don Juan', 'Villablino', 'Fabero'],
  'Lleida': ['Lleida', 'Tàrrega', 'Balaguer', "La Seu d'Urgell", 'Mollerussa', 'Cervera', 'Solsona', 'Tremp', 'Almacelles', 'Alpicat'],
  'Lugo': ['Lugo', 'Monforte de Lemos', 'Viveiro', 'Vilalba', 'Sarria', 'Ribadeo', 'Foz', 'Burela', 'Chantada', 'O Saviñao'],
  'Madrid': ['Madrid', 'Móstoles', 'Alcalá de Henares', 'Fuenlabrada', 'Leganés', 'Getafe', 'Alcorcón', 'Torrejón de Ardoz', 'Parla', 'Alcobendas', 'Las Rozas de Madrid', 'Pozuelo de Alarcón', 'Rivas-Vaciamadrid', 'Coslada', 'Colmenar Viejo', 'San Sebastián de los Reyes', 'Majadahonda', 'Aranjuez', 'Boadilla del Monte', 'Valdemoro'],
  'Málaga': ['Málaga', 'Marbella', 'Mijas', 'Fuengirola', 'Vélez-Málaga', 'Torremolinos', 'Estepona', 'Benalmádena', 'Antequera', 'Rincón de la Victoria', 'Ronda', 'Cártama', 'Coín', 'Alhaurín de la Torre', 'Nerja'],
  'Murcia': ['Murcia', 'Cartagena', 'Lorca', 'Molina de Segura', 'Alcantarilla', 'Cieza', 'Yecla', 'Totana', 'Caravaca de la Cruz', 'San Javier', 'Mazarrón', 'Águilas', 'Las Torres de Cotillas', 'Alhama de Murcia', 'Jumilla'],
  'Navarra': ['Pamplona', 'Tudela', 'Barañáin', 'Burlada', 'Estella-Lizarra', 'Tafalla', 'Villava', 'Ansoáin', 'Zizur Mayor', 'Alsasua', 'Berriozar', 'Corella', 'Elizondo', 'Sangüesa'],
  'Ourense': ['Ourense', 'O Barco de Valdeorras', 'Verín', 'Carballino', 'Xinzo de Limia', 'Ribadavia', 'Allariz', 'Celanova', 'A Rúa', 'O Carballiño'],
  'Palencia': ['Palencia', 'Aguilar de Campoo', 'Venta de Baños', 'Villamuriel de Cerrato', 'Saldaña', 'Carrión de los Condes', 'Dueñas', 'Guardo', 'Herrera de Pisuerga', 'Cervera de Pisuerga'],
  'Pontevedra': ['Vigo', 'Pontevedra', 'Vilagarcía de Arousa', 'Redondela', 'Marín', 'O Porriño', 'Lalín', 'Tui', 'Cambados', 'Cangas', 'Poio', 'Nigrán', 'Sanxenxo', 'Gondomar'],
  'Salamanca': ['Salamanca', 'Ciudad Rodrigo', 'Béjar', 'Santa Marta de Tormes', 'Peñaranda de Bracamonte', 'Guijuelo', 'Alba de Tormes', 'Vitigudino', 'Ledesma', 'Tamames'],
  'Santa Cruz de Tenerife': ['Santa Cruz de Tenerife', 'San Cristóbal de La Laguna', 'Arona', 'Adeje', 'La Orotava', 'Granadilla de Abona', 'Los Realejos', 'Puerto de la Cruz', 'Candelaria', 'Tacoronte', 'Icod de los Vinos', 'Güímar', 'Los Llanos de Aridane', 'El Rosario', 'Tegueste'],
  'Segovia': ['Segovia', 'Cuéllar', 'San Ildefonso', 'Carbonero el Mayor', 'Nava de la Asunción', 'Cantalejo', 'El Espinar', 'Palazuelos de Eresma', 'Sepúlveda', 'Riaza'],
  'Sevilla': ['Sevilla', 'Dos Hermanas', 'Alcalá de Guadaíra', 'Utrera', 'Écija', 'Carmona', 'Lebrija', 'Morón de la Frontera', 'La Rinconada', 'Coria del Río', 'Osuna', 'Mairena del Aljarafe', 'Lora del Río', 'Brenes', 'Marchena'],
  'Soria': ['Soria', 'Almazán', 'Ólvega', 'Berlanga de Duero', 'Ágreda', 'San Esteban de Gormaz', 'El Burgo de Osma', 'Garray', 'Covaleda', 'Medinaceli'],
  'Tarragona': ['Tarragona', 'Reus', 'Salou', 'Cambrils', 'Valls', 'El Vendrell', 'Tortosa', 'Amposta', 'Montblanc', 'Deltebre', 'La Canonja', 'Constantí', 'Roquetes', 'Cunit', 'Altafulla'],
  'Teruel': ['Teruel', 'Alcañiz', 'Andorra', 'Calamocha', 'Montalbán', 'Utrillas', 'Calanda', 'Alcorisa', 'Híjar', 'Monreal del Campo'],
  'Toledo': ['Toledo', 'Talavera de la Reina', 'Illescas', 'Seseña', 'Torrijos', 'Ocaña', 'Fuensalida', 'Madridejos', 'Consuegra', 'Quintanar de la Orden', 'Bargas', 'Villacañas', 'La Puebla de Montalbán', 'Mora', 'Yepes'],
  'Valencia': ['Valencia', 'Torrent', 'Paterna', 'Sagunto', 'Gandia', 'Paiporta', 'Burjassot', 'Alzira', 'Sueca', 'Aldaia', 'Mislata', 'Xàtiva', 'Cullera', 'Alaquàs', 'Massamagrell', 'Oliva', 'Pobla de Vallbona', 'Algemesí', 'Riba-roja de Túria', "L'Eliana"],
  'Valladolid': ['Valladolid', 'Laguna de Duero', 'Medina del Campo', 'Arroyo de la Encomienda', 'Tordesillas', 'Tudela de Duero', 'Íscar', 'Peñafiel', 'Simancas', 'Cistérniga', 'La Cistérniga', 'Boecillo', 'Portillo', 'Olmedo', 'Villabrágima'],
  'Vizcaya': ['Bilbao', 'Barakaldo', 'Getxo', 'Portugalete', 'Santurtzi', 'Basauri', 'Leioa', 'Galdakao', 'Durango', 'Erandio', 'Sestao', 'Gernika-Lumo', 'Lezama', 'Mungia', 'Ermua'],
  'Zamora': ['Zamora', 'Benavente', 'Toro', 'Morales del Vino', 'Villalpando', 'Puebla de Sanabria', 'Fuentesaúco', 'Tábara', 'Villafáfila', 'Fermoselle'],
  'Zaragoza': ['Zaragoza', 'Calatayud', 'Ejea de los Caballeros', 'Tarazona', 'Utebo', 'Cuarte de Huerva', 'Caspe', 'Alagón', 'La Almunia de Doña Godina', 'Borja', 'Fraga', 'Tauste', 'Zuera', 'Daroca', 'Mequinenza'],
};
